### ISSUE TITLE
make fails because of dependency issue 

### ISSUE THREAD

**Issue by vishnoianil** [openshift-metal3/dev-scripts#922]
**Describe the bug**
On my centos 7 machine (24 cpu / 64g ram), i installed the libvirt +OVNKubernetes setup using dev-scripts. I believe i was on commit `fbec3519b37ad045cb2642ef672d32ed3e9dd8a5`. Today i pulled the latest code (commit `d2ff287549e2a749551aa2ba105dbcbd01e31e4b`) and tried to setup the same cluster (no configuration change) and it failed with the following error. Looks like it tries to update the libonig, but fails because of broken dependency and as a result make fails.

+ sudo yum -y update
```
Loaded plugins: fastestmirror, priorities
Loading mirror speeds from cached hostfile
 * base: repo1.ash.innoscale.net
 * epel: packages.oit.ncsu.edu
 * extras: mirror.linux.duke.edu
 * updates: repo1.ash.innoscale.net
7 packages excluded due to repository priority protections
Resolving Dependencies
--> Running transaction check
---> Package oniguruma.x86_64 0:5.9.5-3.el7 will be updated
--> Processing Dependency: libonig.so.2()(64bit) for package: jq-1.6-1.el7.x86_64
---> Package oniguruma.x86_64 0:6.7.0-1.el7 will be an update
--> Finished Dependency Resolution
Error: Package: jq-1.6-1.el7.x86_64 (@epel)
           Requires: libonig.so.2()(64bit)
           Removing: oniguruma-5.9.5-3.el7.x86_64 (@epel)
               libonig.so.2()(64bit)
           Updated By: oniguruma-6.7.0-1.el7.x86_64 (delorean-master-testing)
              ~libonig.so.4()(64bit)
 You could try using --skip-broken to work around the problem
 You could try running: rpm -Va --nofiles --nodigest
make: *** [requirements] Error 1
```

To workaround, if you remove oniguruma-5.9.5 manually and run make again, it will pass this error, but just want to report it so it can be fixed.

**To Reproduce**
Move to commit `fbec3519b37ad045cb2642ef672d32ed3e9dd8a5`, fire make with following configuration
`export PULL_SECRET='REMOVED'
set -x

export LANG=en_US.UTF-8
export WORKING_DIR="/home/dev-scripts"
export NUM_MASTERS=3
export NUM_WORKERS=1
export PRO_IF="em2"
export INT_IF="em4"
export CLUSTER_NAME="mycluster"
export BASE_DOMAIN="dev.metalkube.org"
export NODES_PLATFORM=libvirt
export NETWORK_TYPE="OVNKubernetes"`

now make clean and move to latest commit and fire make again. It should hit this error.

**Expected/observed behavior**
yum update should not failed, if script is taking care of the installation of the required dependency (specially when user didn't do any new package installation manually).

**Comment by hardys** [comment]
This should have been fixed via https://github.com/metal3-io/metal3-dev-env/pull/203 - can you confirm the version of metal3-dev-env in your environment?  It is cloned either to the WORKING_DIR (default /opt/dev-scripts), or perhaps you have a stale local checkout using the METAL3_DEV_ENV variable?

**Comment by cybertron** [comment]
My metal3-dev-env has that fix and I'm still hitting this.

**Comment by cybertron** [comment]
It appears to be related to https://github.com/metal3-io/metal3-dev-env/pull/203#issuecomment-580234041

The fix assumes the tripleo repos will be disabled during make clean, but that isn't the case right now. As a result the first yum update still hits this problem on a re-deploy.

**Comment by vishnoianil** [comment]
> This should have been fixed via [metal3-io/metal3-dev-env#203](https://github.com/metal3-io/metal3-dev-env/pull/203) - can you confirm the version of metal3-dev-env in your environment? It is cloned either to the WORKING_DIR, or perhaps you have a stale local checkout using the METAL3_DEV_ENV variable?

I just checked and my metal3-dev-env clone has this fix and it's still hitting the issue.
`commit 19bfb29e3cd787450947734548308073e72ae191
Merge: f9d17bf ac701a3
Author: Stephen Benjamin <stephen@redhat.com>
Date:   Wed Jan 29 12:30:44 2020 -0500

    Hack to fix oniguruma conflict on CentOS 7 (#203)

    Hack to fix oniguruma conflict on CentOS 7`
I can toss my working-dir and try again to make sure it's not because of the stale code. By version of metal3-dev-env you mean `v1alpha2` or are you pointing to something else?

**Comment by vishnoianil** [comment]
@hardys i tried after tossing the WORKING_DIR but still see the same issue.

**Comment by hardys** [comment]
https://github.com/openshift-metal3/dev-scripts/pull/923 should fix this issue, thanks @cybertron!

**Comment by vishnoianil** [comment]
@hardys Yes, i just verified, i don't see this issue anymore in my environment.
